image: microsoft/dotnet:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet build
  artifacts:
    paths:
      - src/UniTube.Core/bin/
      - src/UniTube.GTK/bin/

test:
  stage: test
  script:
    - dotnet test
